### ISSUE TITLE
Build Failure: File exists (os error 17)

### ISSUE THREAD

**Issue by esibun** [ezKEa/aagl-gtk-on-nix#162] opened 2024-12-17 22:04 UTC
Hello,

One of the upstream Nixpkgs commits seems to have broken the steam-run-custom package provided with AAGL.  When trying to build with the latest nixpkgs stable version, the following error is thrown:

```
error: builder for '/nix/store/hmimz0q4ms12vkk9sy7dq2lw9aqh7pgk-steam-run-fhsenv-rootfs.drv' failed with exit code 1;
       last 5 log lines:
       > structuredAttrs is enabled
       > Error: When symlinking "/nix/store/acwpfdc1aq36bcrwfz4gsdrb59kvswi2-pipewire-1.2.6/share/locale/bn_IN/LC_MESSAGES" to "/nix/store/s9xd5hb23rrxbkkrmzmnqkpd98nnr2lj-steam-run-fhsenv-rootfs/usr/share/locale/bn_IN/LC_MESSAGES"
       >
       > Caused by:
       >     File exists (os error 17)
       For full logs, run 'nix log /nix/store/hmimz0q4ms12vkk9sy7dq2lw9aqh7pgk-steam-run-fhsenv-rootfs.drv'.
error: 1 dependencies of derivation '/nix/store/ns41jknx8x735h48hw769w2261wd1g3j-steam-run-bwrap.drv' failed to build
error: 1 dependencies of derivation '/nix/store/z7q02r2myzl5spb8ahnm3y0z96ip041s-steam-run.drv' failed to build
error: 1 dependencies of derivation '/nix/store/frkw2p4xa4z2y27zyj5f0pfq6c7qf64r-anime-game-launcher.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jr032amj2bnarhkzswwj6sbrgpy4n5ap-anime-game-launcher-3.13.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/98xm979y6i7f4ha4xy71vzg8vw448ibi-anime-game-launcher-3.13.0-fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kzmnmhl5p9y08gws6mviw8a7k1mvd1x7-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/n5jnxdsn5wcsdm4bdnimc73jz10vxfkp-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wss28b3cb8d4x0n0hinr6imdmkhzj1jr-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/34y2gv78d7ja40h2851i5gq0ahk1rk96-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ravlfxdsmx5hkmmqzw2y9gsdafiwr8xk-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/75ikrvz29y5w2id67n6y0rl0nijjrwlj-nixos-system-esi-nixos-24.11.20241213.314e12b.drv' failed to build
```

I bisected locally and determined the offending upstream commit is somewhere between a0f3e10d94359665dba45b71b4227b0aeb851f8e and 314e12ba369ccdb9b352a4db26ff419f7c49fa84.  For now, pinning AAGL to use an older revision of nixpkgs works around the issue, but I'm suspecting that something regarding the FHSEnv code in this repo needs to be updated to work with newer revisions.

**Comment by ezKEa** [comment] 2024-12-18 00:40
Are you using any overlays that aren't committed to your config? I can't reproduce this even when evaluating your config repo. Also, can you tell me if it happens when you use the `main` branch? (the repo will complain about version mismatch but main and stable haven't diverged very far so it's fine

**Comment by esibun** [comment] 2024-12-18 02:34
`main` works fine for me; I just saw #161 and applied it.  Looks like it just needs a backport?

**Comment by ezKEa** [comment] 2024-12-18 16:33
backported https://github.com/ezKEa/aagl-gtk-on-nix/commit/c1c8c462acff8f54059468f2d87fc6216deb571b

**Closed by ezKEa** 2024-12-18 16:33 UTC
